Revert upgrading sqlparser and attempted release
TIL that `cargo publish` blocks Git-versioned dependencies:

```
error: all dependencies must have a version specified when publishing.
dependency `sqlparser` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

So we cannot do this upgrade and must wait for the next sqlparser release.